config/routes.rb
# Defines the app's routes
# @author Chris Loftus
Rails.application.routes.draw do
  resources :users do
    # We add a special route to support the search field
    get 'search', on: :collection
  end

  # the REST API routes
  namespace :api, defaults: {format: :json} do
    resources :users, except: [:new, :edit] do
      get 'search', on: :collection
    end
    resources :topics, except: [:new, :edit, :destroy, :update]
  end

  # No point allowing the editing or update of an existing broadcast
  resources :broadcasts, except: [:edit, :update]

  # A singleton resource and so no paths requiring ids are generated
  # Also, don't want to support editing of the session
  resource :session, only: [:new, :create, :destroy]

  # This is just to support the landing page
  get 'home', to: 'home#index', as: :home

  resources :topics, except: [:edit, :update, :create]

  # no point showing all posts in a separate page or showing specific posts
  resources :posts, except: [:index, :show, :edit]

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates_presence_of :title, :date

  belongs_to :user, :optional => true
  has_many :posts, dependent: :destroy

  self.per_page = 8

  def mark_read_posts(user_id)
    # 1. Get all unread posts for this topic by the logged in user
    # 2. Iterate over them and insert into PostsRead
    u_posts = unread_posts(user_id)
    u_posts.each do |p|
      pr = PostsRead.new
      pr.user_id = user_id
      pr.post_id = p.id
      pr.topic_id = self.id
      pr.save
    end
  end

  def unread_posts(user_id)
    # 1. Get all posts of this topic
    # 2. Get all PostsRead for the logged in user of this topic
    # 3. Extract post IDs of the PostsRead
    # 4. Get all Posts which has been read by the logged in user
    # 5. Return the difference of total_posts and read_posts back to the caller
    total_posts = self.posts
    posts_read = PostsRead.where(user_id: user_id, topic_id: self.id)
    ids = []
    posts_read.each do |pr|
      ids.push(pr.post_id)
    end
    read_posts = Post.where(id: ids)
    return total_posts - read_posts
  end

  def post_wrappers
    # 1. Iterate over all posts of this topic
    # 2. Find the parent node
    # 3. Create an empty array for the output
    # 4. Perform a traversal over the nodes
    # 5. At each node, find the depth, construct a PostWrapper and store in out
    root = nil
    self.posts.each do |p|
      if p.is_parent
        root = p
        break
      end
    end
    out = Array.new
    traverse(root, out)
    return out
  end

  def traverse(root, out)
    offset = root.number_of_parents
    out.push(PostWrapper.new(root, offset))
    if root.children.exists?
      sorted = root.children.sort_by(&:date)
      sorted.each do |child|
        self.traverse(child, out)
      end
    end
  end
end

class PostWrapper
  attr_accessor :post, :offset
  def initialize(post, offset)
    @post = post
    @offset = offset
  end
end

app/controllers/api/topics_controller.rb
class API::TopicsController < API::ApplicationController

  before_action :set_topic, only: [:show]

  rescue_from ActiveRecord::RecordNotFound, with: :show_record_not_found

  # GET /api/topics.json
  def index
    if params.key?(:all)
      @topics = Topic.all.order('date DESC')
    else
      @topics = Topic.paginate(page: params[:page], per_page: params[:per_page])
                  .order('date DESC')
    end
  end

  # GET /api/topics/1.json
  def show
    respond_to do |format|
      format.json
    end
  end

  # POST /api/topics.json
  def create
    # 1. Create a new post based on the params
    # 2. Assign a date and user if required
    # 3. Create and assign a topic for the post
    # 4. Save all
    @post = Post.new(post_params)
    if !params.has_key?(:anonymous)
        @post.user = current_user.user
    end
    current_date = Time.now

    if @post.topic.nil?
      # post in not a reply to a different post
      @topic = Topic.new
      @topic.title = @post.title
      @topic.user = @post.user
      @topic.date = current_date
      @topic.save
      @post.topic = @topic
    end
    @post.date = current_date

    respond_to do |format|
      if @post.save
        format.json { render :show, status: :created, location: @topic }
      else
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_topic
    @topic = Topic.find(params[:id])
  end

  def show_record_not_found(exception)
    respond_to do |format|
      format.json {
        render json: '{Thread does not exist.}',
               status: :unprocessable_entity
      }
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  # Note that the user_details_attributes call used in the non-API UsersController
  # class did not work for REST client requests. It may be that nested attributes
  # as supported by the nested_attributes call in the User model may not work
  # with non-form based requests. Further investigation is required. Consequently,
  # the data is sent in a unnested form and the objects created and tied
  # together explicitly in the create action.
  def post_params
    params.require(:post).permit(:title, :body, :date, :user_id, :parent_id, :topic_id)
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :destroy]

  # GET /topics
  def index
    @topics = Topic.paginate(page: params[:page], per_page: params[:per_page])
                .order('date DESC')
  end

  # GET /topics/1
  def show
    @current_page = params[:page]
  end

  # GET /topics/new
  def new
    @post = Post.new
  end

  # DELETE /topics/1
  def destroy
    respond_to do |format|
      if is_owner_or_admin(@topic)
        @topic.destroy
        format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      else
        format.html { redirect_to topics_url, notice: 'You are not the owner of this thread!' }
      end
    end
  end

  def is_owner_or_admin(topic)
    if topic.user.nil? && is_admin?
      return true
    elsif (!topic.user.nil? && (is_admin? || topic.user.id == current_user.id))
      return true
    else
      return false
    end
  end

  helper_method :is_owner_or_admin

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :date, :user_id)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_with(model: topic, local: true) do |form| %>
  <% if topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :topic_title %>
  </div>

  <div class="input-field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :topic_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Forum</h2>

<%= link_to 'Create Thread', new_topic_path, class: 'btn', id: 'create-thread' %>
<table id="topics-table" class="bordered">
  <thead>
    <tr>
      <th>Date</th>
      <th>Title</th>
      <th>Author</th>
      <th>Unread posts</th>
      <th>Total number posts</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.date.strftime("%d/%m/%y %H:%M:%S") %></td>
        <td><%= topic.title %></td>
        <% if topic.user %>
          <td><%= topic.user.firstname %> <%= topic.user.surname %></td>
        <% else %>
          <td>anonymous</td>
        <% end %>
        <%
           u_posts = topic.unread_posts(current_user.id)
           if u_posts.length == 0
        %>
          <td><p class="right-align clear-margin">0</p></td>
        <% else %>
          <td><span class="new badge"><%= u_posts.length %></span></td>
        <% end %>
        <td><p class="right-align clear-margin"><%= topic.posts.length %></p></td>
        <td><%= link_to 'Show', topic_path(topic, page: @topics.current_page) %></td>
        <td><%= link_to_if is_owner_or_admin(topic), 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="digg_pagination">
  <div>
    <%= page_entries_info @topics %>
  </div>
  <%= will_paginate @topics, container: false %>
</div>

app/views/topics/new.html.erb
<h2>New Thread</h2>

<%= render '/posts/form', post: @post %>

  <div class="col s11">
    <%= link_to 'Back', topics_path, class: 'btn-flat' %>
  </div>
</div>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Forum</h2>
<%= link_to 'Back', topics_path(page: @current_page), class: "btn-flat"%>
<% @topic.post_wrappers.each do |pw| %>
  <div class="row">
    <div class="col s<%= 12 - pw.offset %> offset-s<%= pw.offset %>">
      <div class="card">
        <div class="card-content">
          <span class="card-title">
            <div class="row">
              <div class="col s7"><%= pw.post.title %></div>
              <div class="col s5">
                <% if pw.post.user %>
                  <h6 class="right-align grey-text"><%= pw.post.user.firstname%> <%= pw.post.user.surname%> - <%= pw.post.date.strftime("%d/%m/%y %H:%M:%S") %></h6>
                <% else %>
                  <h6 class="right-align grey-text">anonymous - <%= pw.post.date.strftime("%d/%m/%y %H:%M:%S") %></h6>
                <% end %>
              </div>
            </div>
          </span>
          <p><%= pw.post.body %></p>
        </div>
        <div class="card-action">
          <%= link_to 'Reply', new_post_path(:topic_id => @topic.id, :post_id => pw.post.id) %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<% @topic.mark_read_posts(current_user.id) %>